### ISSUE TITLE
bio_ik dependency

### ISSUE THREAD

**Issue by mahaarbo** [itk-thrivaldi/thrivaldi_common#1]
@ivareri :Trying to run `rosdep install`, but it can't locate `bio_ik`.

Was it: [TAMS-Group/bio_ik](https://github.com/TAMS-Group/bio_ik) you used?

**Comment by ivareri** [comment]
Yes. 

While bio_ik seems to have some nice features, I've been considering dropping the move group using it, along with the dependency. I was not happy with the paths that basic testing produced, but have been holding off further testing while waiting for https://github.com/TAMS-Group/bio_ik/issues/1 .

**Comment by mahaarbo** [comment]
I'd say move it to a branch?
Then we can merge when and if we want the features?
We're using IKFast otherwise, right?

**Comment by ivareri** [comment]
I'll create a branch, that way it is easy to test while not introducing extra dependencies for those not wanting to use it.

As for IKFast: The plugin generation does not currently support > 7 DOF[1]. As i understand it, this is not a limitation of IKFast, but in the plugin generation step. Therefore, it depends on the selected move/planning group if IKFast is used or not. 

Both `floor_manipulator` and `gantry_manipulator` use IKFast as they are only 6 DOF. 

The `gantry_with_manipulator` and `robot` group uses KDL as they are 9 and 15 DOF. 

--
1: http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast_tutorial.html
